app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

admin:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:admin }

AjoutEvent:
    path:     /AjoutEvent
    defaults: { _controller: AppBundle:Annonce:AjoutEvent }

AfficherOffre:
    path:     /AfficherOffre/{typeAnnonce}
    defaults: { _controller: AppBundle:Annonce:AfficherOffre }

AfficherOffreDetail:
    path:     /AfficherOffreDetail/{id}
    defaults: { _controller: AppBundle:Annonce:AfficherOffreDetail }

AfficherEvent:
    path:     /AfficherEvent/{typeAnnonce}
    defaults: { _controller: AppBundle:Annonce:AfficherEvent }

AfficherEventDetail:
    path:     /AfficherEventDetail/{id}
    defaults: { _controller: AppBundle:Annonce:AfficherEventDetail }

DeleteEvent:
    path:     /DeleteEvent/{id}
    defaults: { _controller: AppBundle:Annonce:DeleteEvent }

modifierEvent:
    path:     /modifierEvent/{id}
    defaults: { _controller: AppBundle:Annonce:modifierEvent }

modifierOffre:
    path:     /modifierOffre/{id}
    defaults: { _controller: AppBundle:Annonce:modifierOffre }

AjoutOffre:
    path:     /AjoutOffre
    defaults: { _controller: AppBundle:Annonce:AjoutOffre }

DeleteOffre:
    path:     /DeleteOffre/{id}
    defaults: { _controller: AppBundle:Annonce:DeleteOffre }