app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

admin:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:admin }

defis:
    path:     /listdefis
    defaults: { _controller: AppBundle:Defis:index }

battle:
    path:     /listedefis/{defi}
    defaults: { _controller: AppBundle:Defis:show }

join:
    path:     /listedefis/{defi}
    defaults: { _controller: AppBundle:MembresDefis:Join }

add:
    path:     /add/{defi}
    defaults: { _controller: AppBundle:Discussion:add }

check:
    path:     /check/{defi}
    defaults: { _controller: AppBundle:Checkin:check }

checked:
    path:     /check/{defi}
    defaults: { _controller: AppBundle:Checkin:do }

delete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:Defis:delete }

deletediscussion:
    path:     /deletediscussion/{defi}/{id}
    defaults: { _controller: AppBundle:Discussion:deletediscussion }

update:
    path:     /edit/{defi}/{id}
    defaults: { _controller: AppBundle:Discussion:update }

forum:
    path:     /forum
    defaults: { _controller: AppBundle:Question:show }

forumcat:
    path:     /forum/{cat}
    defaults: { _controller: AppBundle:Question:findQues }

Question:
    path:     /AddQuestion
    defaults: { _controller: AppBundle:Question:addQuest }

reponse:
    path:     /Question/{id}
    defaults: { _controller: AppBundle:Reponse:Show }

editQuestion:
    path:     /editQuestion/{id}
    defaults: { _controller: AppBundle:Question:editQuestion }

deleteQuestion:
    path:     /deleteQuestion/{id}
    defaults: { _controller: AppBundle:Question:editQuestion }

editResponse:
    path:     /editRep/{idq}/{idr}
    defaults: { _controller: AppBundle:Reponse:editReponse }

deleteResponse:
    path:     /delete/{idq}/{idr}
    defaults: { _controller: AppBundle:Reponse:deleteresponse }

addrep:
    path:     /Question/{id}
    defaults: { _controller: AppBundle:Reponse:addRep }

like:
    path:     /Question/{idq}/{idr}
    defaults: { _controller: AppBundle:Reponse:like }

stat:
    path:     /stat
    defaults: { _controller: AppBundle:Admin:stat}

confquest:
    path:     /ConfirmQuestion
    defaults: { _controller: AppBundle:Admin:Question}

confirmquest:
    path:     /ConfirmQuestion/{id}
    defaults: { _controller: AppBundle:Admin:viewQuestion}

approve:
    path:     /approve/{id}
    defaults: { _controller: AppBundle:Admin:approve}

