app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

admin:
    path:     /admin
    defaults: { _controller: AppBundle:Admin:admin }

AjoutAnnonce:
    path:     /AjoutAnnonce
    defaults: { _controller: AppBundle:Annonce:AjoutAnnonce }

AfficherOffre:
    path:     /AfficherOffre
    defaults: { _controller: AppBundle:Annonce:AfficherOffre }

AfficherOffreDetail:
    path:     /AfficherOffre/{id}
    defaults: { _controller: AppBundle:Annonce:AfficherOffreDetail }

AfficherEvent:
    path:     /AfficherEvent
    defaults: { _controller: AppBundle:Annonce:AfficherEvent }

AfficherEventDetail:
    path:     /AfficherEvent/{id}
    defaults: { _controller: AppBundle:Annonce:AfficherEventDetail }
