reponsequiz_index:
    path:     /
    defaults: { _controller: "AppBundle:reponseQuiz:index" }
    methods:  GET

reponsequiz_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:reponseQuiz:show" }
    methods:  GET

reponsequiz_new:
    path:     /new
    defaults: { _controller: "AppBundle:reponseQuiz:new" }
    methods:  [GET, POST]

reponsequiz_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:reponseQuiz:edit" }
    methods:  [GET, POST]

reponsequiz_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:reponseQuiz:delete" }
    methods:  DELETE
