resulatquiz_index:
    path:     /
    defaults: { _controller: "AppBundle:resulatQuiz:index" }
    methods:  GET

resulatquiz_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:resulatQuiz:show" }
    methods:  GET

resulatquiz_new:
    path:     /new
    defaults: { _controller: "AppBundle:resulatQuiz:new" }
    methods:  [GET, POST]

resulatquiz_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:resulatQuiz:edit" }
    methods:  [GET, POST]

resulatquiz_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:resulatQuiz:delete" }
    methods:  DELETE
